[env:esp32dev]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_build.partitions = default.csv
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=0
